CREATE TABLE SQLCheck (
  ID varchar(10),
  Name  varchar(100),
  DateCheck DATE,
  CheckIn BIT,
  CheckOut BIT,
  TimesLate int
)

ALTER TABLE SQLCheck
ADD TimeCheckIn DATETIME,
    TimeCheckOut DATETIME;

ALTER TABLE SQLCheck
ALTER COLUMN ID varchar(10) NOT NULL
ALTER TABLE SQLCheck
ALTER COLUMN TimeCheckIn DATETIME NOT NULL
ALTER TABLE SQLCheck
ALTER COLUMN TimeCheckOut DATETIME NOT NULL
ALTER TABLE SQLCheck ADD CONSTRAINT PK_SQLCheck PRIMARY KEY (ID,TimeCheckIn,TimeCheckOut) ;

SELECT * FROM SQLCheck WHERE ID = 'EMP12345' ---and MONTH(TimeCheckIn) = 5 AND MONTH(TimeCheckOut) = 5
SELECT DateCheck,TimeCheckIn,TimeCheckOut FROM SQLCheck WHERE ID = 'EMP12345' and MONTH(DateCheck) = 01